### PR TITLE
Implemented the hook_complete

### PR DESCRIPTION
**Pull request by adrian-cid**
Once you follow the configuration instructions inside https://github.com/drush-ops/drush/blob/master/drush.complete.sh you can do this:

Write the following:
`drush boilerplate-hi eve`
and push tab to autocomplete:
`drush boilerplate-hi everyone`

### CODE REVIEW

**Comment by aramboyajyan** [comment]
Thanks Adrian! I'll have a look at it shortly and merge if all is fine.

**Comment by adrian-cid** [comment]
Have you see if the code its fine?

**Comment by aramboyajyan** [comment]
I'm guilty - I forgot about this, sorry :(

Will check it now (like, right now) and get back to you!

**Comment by aramboyajyan** [comment]
Just merged - thanks!

**Pull request merged**
